#!/bin/bash
# shellcheck disable=SC2016,SC2046,SC2066,SC2068,SC2086,SC2162,SC2317

KERNEL_VERSION="$1"

if [ ${#TERM} -gt 0 ] && [ ! $TERM == "unknown" ]; then
    clear
fi

###########################################################################################################
##
##  Forked from: https://github.com/slyfox1186/Windows-WSL2-Kernel-build-script
##  Version: 1.0
##  Updated: 04.19.23
##
##  Updated 2024-06-21
##  Version 2.0
##
###########################################################################################################

script_ver='2.0'

##
## Set the number of processes to cores * 2
##
cpu_cores="$(grep ^cpu\\scores '/proc/cpuinfo' | uniq | awk '{print $4 * 2}')"

##
## Download the Microsoft kernel source
##
download()
{
    dl_path="$PWD"
    dl_file="${2:-"${1##*/}"}"

    if [[ "$dl_file" =~ tar. ]]; then
        target_dir="${dl_file%.*}"
        target_dir="${3:-"${target_dir%.*}"}"
    else
        target_dir="${3:-"${dl_file%.*}"}"
    fi

    if [ ! -f "$dl_path/$dl_file" ]; then
        echo "Downloading $1 as ${dl_path}/${dl_file}"
        if ! curl -Lso "$dl_path/$dl_file" "$1"; then
            echo
            echo "The script failed to download \"$1\" and will try again in 10 seconds"
            sleep 10
            echo
            if ! curl -Lso "$dl_path/$dl_file" "$1"; then
                echo
                echo "The script failed to download \"$1\" two times and will exit the build"
                echo
            fi
        fi
        echo 'Download Completed'
        echo
    else
        echo "$dl_file is already downloaded"
    fi

    echo "Extracting to \"${dl_path}/${target_dir}\"..."
    mkdir -p "$dl_path/$target_dir"
    
    if [ -n "$3" ]; then
        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" &>/dev/null; then
            echo "Failed to extract $dl_file"
            exit 1
        fi
    else
        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" --strip-components 1 &>/dev/null; then
            echo "Failed to extract $dl_file"
            exit 1
        fi
    fi

    echo "File extracted: $dl_file"

    cd "$dl_path/$target_dir" || exit 1
}

installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }

echo "WSL2-Custom-Kernel build script v$script_ver"
echo '======================================'
echo
echo "The script will utilize ( $cpu_cores cpu cores )"
echo
echo "Downloading Microsoft kernel from version ${KERNEL_VERSION}..."
echo '===================================='

download "https://api.github.com/repos/microsoft/WSL2-Linux-Kernel/tarball/linux-msft-wsl-${KERNEL_VERSION}" "linux-msft-wsl-${KERNEL_VERSION}.tar.gz"

echo
echo "Building custom kernel..."
echo '===================================='
make CC="ccache gcc" KCONFIG_CONFIG="../config-wsl" -j "$cpu_cores"

echo
echo '===================================='
echo "Build Complete"
echo '===================================='
